# 把網路圖型資料與地點位置結合

In [1]:
%matplotlib inline

In [2]:
import pandas as pd

## 1. 把資料放到 pandas 中

In [158]:
df = pd.read_csv("./../../small_set/TTS1.csv", header=None , encoding="big5")

In [159]:
df.columns = ["Status_code", "Mail_num", "Mail_date", 
             "Mail_time", "OP_office", "other"]

In [160]:
df['Mail_datetime'] = df.Mail_date+" "+df.Mail_time
df.Mail_datetime = pd.to_datetime(df.Mail_datetime)

In [161]:
del df['Mail_date']
del df['Mail_time']
del df['other']

In [183]:
mail_df = df.sort_values(["Mail_num", "Mail_datetime"])

## 2. indexing

In [134]:
df.set_index(["Mail_num", "OP_office"], inplace=True)

In [136]:
df.sort_values(["Mail_num", "Mail_datetime"])

                               Status_code       Mail_datetime
Mail_num             OP_office
00000000000000       330031             Y4 2018-01-01 09:49:04
                     330031             Y4 2018-01-01 09:58:08
                     330031             I4 2018-01-01 14:11:51
                     330031             Y4 2018-01-01 14:23:32
                     330031             I4 2018-01-01 14:52:09
                     330031             I4 2018-01-01 16:15:52
                     900030             Y4 2018-01-02 08:23:15
                     500055             Y4 2018-01-02 08:41:51
                     100029             G2 2018-01-02 09:20:00
                     900030             I4 2018-01-02 14:06:24
                     500055             I4 2018-01-02 14:58:34
                     330031             Y4 2018-01-02 16:29:54
                     330031             I4 2018-01-02 16:41:41
00000000000018       640026             Y4 2018-01-02 08:33:32
                     640026             I4 2018-01-02 12:14:18
00000100000018       640026             Y4 2018-01-02 08:34:02
                     640026             I4 2018-01-02 12:14:18
00000100081117       830024             H4 2018-01-02 13:26:12
00000200023517       220026             G2 2018-01-02 10:16:00
00000410025400       100564             P5 2018-01-01 06:51:07
00000900081117       800586             Y4 2018-01-02 08:20:51
                     800586             I4 2018-01-02 15:33:20
00001130205103       300051             A1 2018-01-02 10:40:00
00001410725500       100564             P5 2018-01-01 06:50:56
00001510725500       100564             P5 2018-01-01 06:50:54
00001810725500       100564             P5 2018-01-01 06:50:49
00003600081117       830584             Y4 2018-01-02 08:36:10
                     830584             I4 2018-01-02 13:39:50
00004000081117       830021             Y4 2018-01-02 08:38:12
                     830021             I4 2018-01-02 15:23:56
...                                    ...                 ...
98329340004770505453 500027             W2 2018-01-01 13:35:24
98402373000020320003 330585             Z4 2018-01-01 16:37:19
98413673000020100004 330585             Z4 2018-01-01 16:38:47
98425970401310350001 360023             I4 2018-01-01 17:10:30
98455600104070       330585             Y4 2018-01-01 14:19:24
                     330585             I4 2018-01-01 14:52:47
98520700102570       100257             V4 2018-01-01 18:02:00
98520900102570       100257             V4 2018-01-01 18:03:00
98521100102570       100257             V4 2018-01-01 18:02:00
98521300102570       100257             V4 2018-01-01 18:02:00
98590700100370       241584             Y4 2018-01-02 08:11:03
                     241584             I4 2018-01-02 11:50:18
98590800100370       100131             A1 2018-01-02 09:33:00
98590900100370       100131             A1 2018-01-02 09:32:00
98625800100270       950016             A1 2018-01-02 13:33:00
                     950580             Z4 2018-01-02 17:01:11
98825442003970892503 100250             Y4 2018-01-01 11:01:25
98939826002910265003 260025             I4 2018-01-01 00:00:00
99042600100370       100062             A1 2018-01-02 10:08:00
99080100100170       800451             A1 2018-01-02 09:10:00
                     800672             Z4 2018-01-02 22:24:21
99170500100170       800451             A1 2018-01-02 20:14:00
                     800672             Z4 2018-01-02 22:21:59
99264124105618       260000             I4 2018-01-01 07:45:00
                     260000             I4 2018-01-01 13:09:00
99443400100070       320030             Y4 2018-01-02 08:26:36
                     320030             I4 2018-01-02 10:12:23
99469500100270       950011             A1 2018-01-02 14:09:00
                     950580             Z4 2018-01-02 17:48:00
99654100100370       100082             A1 2018-01-02 10:13:00

[10000 rows x 2 columns]

In [152]:
df.reset_index()

                  Mail_num  OP_office Status_code       Mail_datetime
0     00000000000000           330031          Y4 2018-01-01 09:49:04
1     00000000000000           330031          Y4 2018-01-01 09:58:08
2     00000000000000           330031          I4 2018-01-01 14:11:51
3     00000000000000           330031          Y4 2018-01-01 14:23:32
4     00000000000000           330031          I4 2018-01-01 14:52:09
5     00000000000000           330031          I4 2018-01-01 16:15:52
6     58668700100170           100250          Y4 2018-01-01 11:06:44
7     59928400100170           220014          I3 2018-01-01 21:10:45
8     75233300100170           704583          P5 2018-01-01 05:30:09
9     19491400101070           320008          A3 2018-01-01 21:40:46
10    84509600101270           500584          A3 2018-01-01 16:40:44
11    96513700101370           100250          Y4 2018-01-01 10:59:45
12    01576100101470           880580          Z4 2018-01-01 12:03:53
13    96114600101570           880580          Z4 2018-01-01 13:04:05
14    14752700101670           420584          Z4 2018-01-01 14:48:17
15    10362200101870           320000          A3 2018-01-01 22:40:46
16    48684100101870           420584          Z4 2018-01-01 14:47:57
17    23799000101970           500600          P4 2018-01-01 21:57:12
18    92557900101970           100250          Y4 2018-01-01 10:57:30
19    82460500102170           100250          Y4 2018-01-01 10:59:52
20    98520700102570           100257          V4 2018-01-01 18:02:00
21    98520900102570           100257          V4 2018-01-01 18:03:00
22    98521100102570           100257          V4 2018-01-01 18:02:00
23    98521300102570           100257          V4 2018-01-01 18:02:00
24    61353900102870           420584          Z4 2018-01-01 14:47:13
25    72423900102970           500600          P4 2018-01-01 21:57:50
26    79068700102970           100250          Y4 2018-01-01 11:00:50
27    32588100103170           100250          Y4 2018-01-01 10:58:12
28    76287300103170           420009          Y4 2018-01-01 15:55:09
29    76287300103170           420009          H4 2018-01-01 17:11:26
...                    ...        ...         ...                 ...
9970  03309940100918           100572          I4 2018-01-02 13:32:55
9971  03310040100918           400009          A1 2018-01-02 15:57:00
9972  03310140100918           400009          A1 2018-01-02 15:57:00
9973  03310240100918           400009          A1 2018-01-02 15:57:00
9974  03310340100918           400009          A1 2018-01-02 15:57:00
9975  03446840100918           400584          Y4 2018-01-02 08:14:21
9976  03446840100918           400584          I4 2018-01-02 12:57:59
9977  03446940100918           400589          Y4 2018-01-02 09:44:54
9978  03446940100918           400589          I4 2018-01-02 17:53:28
9979  03447040100918           400047          Y4 2018-01-02 10:06:55
9980  03447040100918           400047          I4 2018-01-02 14:33:49
9981  03447140100918           400589          Y4 2018-01-02 08:40:19
9982  03447140100918           400589          I4 2018-01-02 12:38:44
9983  03447240100918           100598          Y4 2018-01-02 09:16:59
9984  03447240100918           100598          I4 2018-01-02 13:17:52
9985  03447340100918           400584          Y4 2018-01-02 07:43:25
9986  03447340100918           400584          I4 2018-01-02 15:50:42
9987  03447440100918           200600          Y4 2018-01-02 09:13:08
9988  03447440100918           200600          I4 2018-01-02 13:26:48
9989  03447540100918           420032          Z4 2018-01-02 06:31:36
9990  03447540100918           420037          Y4 2018-01-02 09:26:40
9991  03447540100918           420037          I4 2018-01-02 14:41:45
9992  03447640100918           400584          Y4 2018-01-02 07:21:37
9993  03447640100918           400584          I4 2018-01-02 15:50:44
9994  03447740100918           830600          Y4 2018-01-02 08:37:57
9995  03447740100918           830600          I4 2018-01-02 14:39:43
9996  05579140100916           400009          A1 2018-01-02 16:46:00
9997  05579140100916           400672          Z4 2018-01-02 21:16:18
9998  05579240100916           400009          A1 2018-01-02 16:46:00
9999  05579240100916           400672          Z4 2018-01-02 20:30:37

[10000 rows x 4 columns]

## 3. 載入郵局地點資訊

In [102]:
post_office = pd.read_csv("../Post_All_new.csv")

In [103]:
new_po = post_office[["郵務局號", "局名", "緯度", "經度"]]

In [104]:
new_po.columns=["post_code", "name", "lon", "lat"]

In [105]:
po_dict = new_po.set_index("post_code").to_dict()

In [227]:
def getPOInfo(post_code):
    if isPOCode(post_code):
        return (po_dict['name'][post_code],
                po_dict['lon'][post_code],
                po_dict['lat'][post_code] )
    else:
        return ("%s"%(post_code), "", "")

In [112]:
unique_po_code = set(po_dict['name'].keys())
def isPOCode(post_code):
    if post_code in unique_po_code:
        return True
    else:
        return False

In [229]:
getPOInfo(420584)

('420584', '', '')

## 4. 把郵件資料的郵號跟地點整合

In [189]:
all_mail = {}
all_mail_key = set()
for idx, row in df.iterrows():
    mail_code = row.Mail_num.strip()
    if not mail_code in all_mail_key:
        all_mail[mail_code] = []
        all_mail_key.add(mail_code)
        
    all_mail[mail_code].append( (row.OP_office, row.Mail_datetime, row.Status_code) )

In [194]:
def convert_2_edge(mail_status):
    edges = []
    for idx in range(len(mail_status)-1):
        edges.append( ( mail_status[idx][0], mail_status[idx+1][0], 
                      mail_status[idx][2], mail_status[idx+1][2]))
        
    return edges
# "Y4" -> "H4", 
# "H4" -> "Z2"

mail_status = all_mail['96410700000070']
convert_2_edge(mail_status)

[(540028, 540028, 'Y4', 'Y4'),
 (540028, 540028, 'Y4', 'I4'),
 (540028, 540028, 'I4', 'I4')]

In [195]:
all_edges = [] 
for mail_code in all_mail:
    status_num = len(all_mail[mail_code])
    
    if (status_num) > 1:
        mail_status = all_mail[mail_code]
        all_edges.extend(convert_2_edge(mail_status))

In [205]:
src_nodes = set([ ele[0] for ele in all_edges])
tar_nodes = set([ ele[1] for ele in all_edges]) 
all_nodes = list(src_nodes.union(tar_nodes))

In [206]:
print(len(src_nodes), len(tar_nodes), len(all_nodes))

358 312 385

In [210]:
getPOInfo(all_nodes[12])

('竹東下公館郵局', 24.72617, 121.09508799999999)

In [225]:
src, target, src_state, target_state = all_edges[16]

In [228]:
getPOInfo(src), getPOInfo(target), src_state, target_state

(('220600', '', ''), ('220600', '', ''), 'Y4', 'I4')

In [295]:
import simplekml
kml = simplekml.Kml()

In [298]:
import collections

In [299]:
cnt = collections.Counter(all_edges).most_common(100000)

In [312]:
for (x, val) in cnt:
    
    src, target, src_state, target_state = x
    if target_state == 'I4':
        continue
    print(x, val)
    if isPOCode(src) and isPOCode(target) and not src==target:
       
        src_pnt = getPOInfo(src)
        tar_pnt = getPOInfo(target)
        
#         # point
#         kml.newpoint(name=str(src), 
#                      description=src_pnt[0],
#                      coords=[(src_pnt[2],src_pnt[1])])
#         kml.newpoint(name=str(target), 
#                      description=tar_pnt[0],
#                      coords=[(tar_pnt[2],tar_pnt[1])])
        
        
        # line
        kml.newlinestring(
            name="%s to %s"%(src,target), 
            description="%s to %s"%(src_pnt[0],tar_pnt[0]) ,
            coords=[(src_pnt[2],src_pnt[1]), 
                    (tar_pnt[2],tar_pnt[1])])

(400003, 400672, 'A1', 'Z4') 183
(100012, 91813, 'A1', 'Z4') 95
(400008, 400672, 'A1', 'Z4') 80
(400006, 400672, 'A1', 'Z4') 78
(830000, 800672, 'A1', 'Z4') 73
(704586, 704586, 'Y4', 'H4') 65
(91814, 100587, 'Z4', 'Y4') 50
(400009, 400672, 'A1', 'Z4') 45
(704584, 704584, 'Y4', 'H4') 27
(100581, 100581, 'Y7', 'I7') 25
(800007, 800672, 'A1', 'Z4') 21
(500027, 500027, 'H4', 'W2') 20
(800451, 800672, 'A1', 'Z4') 17
(704585, 704585, 'Y4', 'H4') 17
(800070, 800672, 'A1', 'Z4') 16
(400008, 400008, 'Z1', 'G1') 15
(400008, 400008, 'G1', 'I1') 15
(704586, 704586, 'H4', 'Z4') 14
(300450, 400672, 'A1', 'Z4') 14
(704586, 704586, 'X2', 'H4') 13
(100010, 91813, 'A1', 'Z4') 12
(100591, 100591, 'Y4', 'H4') 11
(704600, 704600, 'Y4', 'H4') 10
(100589, 100589, 'Y4', 'H4') 9
(830038, 800672, 'A1', 'Z4') 9
(950010, 950010, 'A1', 'Z4') 9
(730039, 730039, 'Y4', 'H4') 9
(100599, 100599, 'Y4', 'H4') 8
(830016, 800672, 'A1', 'Z4') 8
(220600, 220600, 'Y4', 'H4') 8
(800054, 800672, 'A1', 'Z4') 8
(950580, 950580, 'P4', 'Y4') 8
(830022, 800672, 'A1', 'Z4') 8
(830011, 800672, 'A1', 'Z4') 8
(800061, 800672, 'A1', 'Z4') 7
(300600, 300600, 'Y4', 'H4') 7
(600584, 600584, 'P4', 'Y4') 7
(400001, 400672, 'A1', 'Z4') 7
(300584, 300450, 'Z1', 'G1') 7
(300584, 300584, 'Y4', 'H4') 7
(100603, 100584, 'Z4', 'Y4') 6
(300450, 300450, 'G1', 'I1') 6
(100601, 100601, 'Y4', 'H4') 6
(220584, 220584, 'Y4', 'H4') 6
(100572, 100572, 'Y7', 'I7') 5
(800069, 800672, 'A1', 'Z4') 5
(100581, 100581, 'Y4', 'H4') 5
(800036, 800672, 'A1', 'Z4') 5
(300048, 300048, 'Z2', 'G2') 5
(730028, 730028, 'Y4', 'H4') 5
(100600, 100600, 'Y4', 'H4') 5
(704672, 600052, 'Z4', 'Y4') 5
(800584, 800584, 'Y4', 'H4') 5
(300600, 300600, 'H4', 'Z2') 4
(100576, 100576, 'Y4', 'H4') 4
(800034, 800672, 'Z4', 'Z4') 4
(830030, 800672, 'A1', 'Z4') 4
(800044, 800672, 'A1', 'Z4') 4
(950580, 950580, 'Y4', 'H4') 4
(100575, 100575, 'Y4', 'H4') 4
(800584, 800584, 'H4', 'Z2') 4
(704020, 704020, 'Y4', 'H4') 4
(950018, 950018, 'A1', 'Z4') 4
(400003, 400003, 'T2', 'Z4') 4
(800034, 800034, 'T2', 'Z4') 4
(100054, 100054, 'T2', 'Z4') 4
(800059, 800672, 'A1', 'Z4') 4
(950014, 950580, 'A1', 'Z4') 3
(400588, 400588, 'Y4', 'H4') 3
(220601, 220601, 'Y4', 'H4') 3
(200031, 200031, 'T2', 'Z4') 3
(330586, 330586, 'Y4', 'H4') 3
(220584, 220583, 'Z4', 'Y4') 3
(800068, 800672, 'A1', 'Z4') 3
(100603, 100603, 'Y4', 'H4') 3
(400008, 400008, 'T2', 'Z4') 3
(300584, 300584, 'H4', 'Z2') 3
(970582, 970582, 'Y4', 'H4') 3
(100587, 100587, 'Y4', 'H4') 3
(100584, 100584, 'Y4', 'H4') 3
(300037, 400672, 'A3', 'Z4') 3
(830009, 800672, 'A1', 'Z4') 3
(100601, 100601, 'I4', 'V2') 3
(220602, 220602, 'Y4', 'H4') 3
(830062, 830062, 'Y4', 'H4') 3
(100601, 100601, 'H4', 'Z2') 3
(100601, 100601, 'V2', 'H4') 3
(950011, 950580, 'A1', 'Z4') 3
(241021, 241021, 'Y4', 'H4') 3
(500600, 500600, 'Z2', 'P4') 3
(830008, 800672, 'A1', 'Z4') 3
(300002, 300002, 'T2', 'Z4') 3
(800050, 800672, 'A1', 'Z4') 3
(704584, 704585, 'Z4', 'Y4') 3
(800056, 800672, 'A1', 'Z4') 2
(100003, 100003, 'T2', 'Z4') 2
(800088, 800672, 'A1', 'Z4') 2
(950008, 950010, 'A1', 'Z4') 2
(900582, 900582, 'Y4', 'H4') 2
(830015, 800672, 'A1', 'Z4') 2
(800584, 800451, 'Z1', 'G1') 2
(704009, 704009, 'Z2', 'G2') 2
(420584, 420002, 'Z4', 'Y4') 2
(220021, 220021, 'T2', 'Z4') 2
(704020, 704027, 'Z2', 'G2') 2
(830055, 830055, 'T2', 'Z4') 2
(540022, 540022, 'H4', 'Z4') 2
(800057, 800672, 'A1', 'Z4') 2
(300038, 300038, 'Y4', 'H4') 2
(800585, 800585, 'Y4', 'H4') 2
(200600, 200600, 'Y4', 'H4') 2
(220014, 220014, 'T2', 'Z4') 2
(540022, 540022, 'X2', 'H4') 2
(830023, 800672, 'A1', 'Z4') 2
(420600, 420600, 'Y4', 'H4') 2
(950027, 950580, 'A1', 'Z4') 2
(704037, 704672, 'A1', 'Z4') 2
(950021, 950021, 'A1', 'Z4') 2
(241036, 330672, 'A1', 'Z4') 2
(100055, 100055, 'G2', 'I2') 2
(704584, 704584, 'Y7', 'I7') 2
(100250, 100184, 'Z1', 'G2') 2
(300037, 300037, 'G1', 'I1') 2
(830062, 830062, 'H4', 'Z2') 2
(220023, 220023, 'T2', 'Z4') 2
(200584, 200584, 'Y4', 'H4') 2
(540022, 540022, 'P4', 'X2') 2
(540582, 540582, 'I4', 'Z4') 2
(730036, 730036, 'Y4', 'H4') 2
(830062, 704672, 'A1', 'Z4') 2
(100576, 100031, 'Z2', 'G2') 2
(330025, 330025, 'Y4', 'H4') 2
(320030, 320030, 'Y4', 'H4') 2
(400601, 400601, 'Y4', 'H4') 2
(300047, 300047, 'Y4', 'H4') 2
(730046, 730046, 'Y4', 'H4') 2
(100079, 100079, 'T2', 'Z4') 2
(100598, 100598, 'Y4', 'H4') 2
(704584, 704018, 'Z2', 'G2') 2
(241011, 241011, 'T2', 'Z4') 2
(100572, 100572, 'Y4', 'H4') 2
(800049, 800672, 'A1', 'Z4') 2
(100250, 100250, 'Y4', 'H4') 2
(704585, 704013, 'Z2', 'G2') 2
(950016, 950580, 'A1', 'Z4') 2
(100029, 100029, 'G2', 'I2') 2
(704585, 704035, 'Z2', 'G2') 2
(420032, 420037, 'Z4', 'Y4') 2
(300052, 300052, 'T2', 'Z4') 2
(800024, 800672, 'A1', 'Z4') 2
(800451, 800451, 'G1', 'I1') 2
(241584, 241584, 'Y4', 'H4') 2
(100589, 100589, 'H4', 'Z2') 2
(830007, 800672, 'A1', 'Z4') 2
(220583, 220583, 'Y4', 'H4') 2
(500584, 500584, 'Y4', 'H4') 2
(704009, 704009, 'Y4', 'H4') 2
(500600, 500045, 'Z1', 'G1') 2
(100148, 100148, 'T2', 'Z4') 2
(704585, 704585, 'X2', 'H4') 2
(800017, 800672, 'A1', 'Z4') 2
(300600, 300037, 'Z1', 'G1') 2
(100581, 91813, 'Z4', 'Z4') 2
(100601, 100158, 'Z1', 'G1') 2
(100602, 100602, 'Y4', 'H4') 2
(400003, 400672, 'Z4', 'Z4') 1
(420027, 420027, 'G1', 'I1') 1
(400601, 400014, 'Z1', 'G1') 1
(100072, 100072, 'S2', 'Z4') 1
(420045, 420045, 'G2', 'I2') 1
(704032, 704032, 'G2', 'I2') 1
(400040, 400040, 'G1', 'I1') 1
(330585, 330585, 'Y4', 'H4') 1
(330025, 330025, 'H4', 'Z2') 1
(400584, 400589, 'Z4', 'Y4') 1
(100601, 100601, 'Y7', 'I7') 1
(330031, 900030, 'I4', 'Y4') 1
(400034, 400034, 'T2', 'Z4') 1
(400584, 400672, 'Z4', 'Z4') 1
(830051, 800672, 'A1', 'Z4') 1
(220086, 220086, 'G2', 'I2') 1
(800068, 800068, 'G2', 'I2') 1
(704600, 704600, 'P4', 'Y4') 1
(300009, 400672, 'A1', 'Z4') 1
(800042, 800672, 'A1', 'Z4') 1
(220052, 220052, 'G2', 'I2') 1
(200584, 200018, 'Z2', 'G2') 1
(320025, 320025, 'Y4', 'H4') 1
(950000, 950000, 'T2', 'Z4') 1
(800017, 800017, 'V3', 'A1') 1
(800061, 800061, 'A1', 'V3') 1
(300584, 300041, 'Y4', 'G3') 1
(800005, 800672, 'A1', 'Z4') 1
(950580, 950580, 'H4', 'Z2') 1
(500600, 500051, 'Z4', 'Z2') 1
(420032, 420032, 'G1', 'I1') 1
(91813, 100118, 'Z4', 'G1') 1
(241584, 91813, 'Z4', 'Z4') 1
(360023, 360023, 'Y4', 'H4') 1
(241021, 241021, 'I4', 'X2') 1
(970021, 970582, 'Z4', 'Z4') 1
(91813, 100055, 'Z4', 'G2') 1
(91814, 100599, 'Z4', 'Y4') 1
(100077, 100077, 'T2', 'Z4') 1
(500055, 330031, 'I4', 'Y4') 1
(704584, 704584, 'X2', 'H4') 1
(830011, 830011, 'V3', 'A1') 1
(100591, 100591, 'H4', 'Z2') 1
(400584, 400065, 'Z1', 'G1') 1
(420600, 420041, 'Z1', 'G1') 1
(730024, 730024, 'Z2', 'G2') 1
(800584, 800583, 'P4', 'Y4') 1
(241001, 241001, 'G1', 'I1') 1
(950000, 950580, 'Z4', 'Z4') 1
(830600, 830600, 'Y4', 'H4') 1
(100096, 100096, 'T2', 'Z4') 1
(970007, 970582, 'Z4', 'Z4') 1
(330031, 330031, 'I4', 'Y4') 1
(500584, 500584, 'H4', 'Z2') 1
(800584, 800584, 'Y7', 'H7') 1
(704672, 730013, 'Z4', 'Y4') 1
(500051, 500051, 'Z2', 'G2') 1
(241600, 241600, 'Y4', 'H4') 1
(100108, 100108, 'G2', 'I2') 1
(800061, 800061, 'V3', 'A1') 1
(704043, 704043, 'T2', 'Z4') 1
(800083, 800672, 'A1', 'Z4') 1
(100118, 100118, 'T2', 'Z4') 1
(420009, 420009, 'H4', 'Z4') 1
(704586, 704586, 'Z4', 'P4') 1
(830048, 800672, 'A1', 'Z4') 1
(241033, 241034, 'Z1', 'G1') 1
(330450, 330450, 'G1', 'I1') 1
(704020, 704045, 'Z2', 'G2') 1
(704584, 704048, 'Z2', 'G2') 1
(220600, 220043, 'P4', 'Y4') 1
(200019, 200019, 'T1', 'Z4') 1
(330039, 330039, 'T2', 'Z4') 1
(100589, 100051, 'Z1', 'G1') 1
(640017, 640017, 'G1', 'I1') 1
(800075, 800672, 'A1', 'Z4') 1
(970582, 970021, 'Z1', 'G1') 1
(260000, 260000, 'T2', 'Z4') 1
(220086, 220086, 'T2', 'Z4') 1
(220584, 220584, 'H4', 'Z2') 1
(300027, 300027, 'T2', 'Z4') 1
(100109, 91814, 'A1', 'Z4') 1
(970582, 970582, 'P4', 'Z1') 1
(500058, 500058, 'Y4', 'H4') 1
(800060, 800060, 'T2', 'Z4') 1
(100603, 100603, 'H4', 'Z2') 1
(330031, 330031, 'G1', 'I1') 1
(830584, 830584, 'X2', 'H7') 1
(800060, 800672, 'Z4', 'Z4') 1
(640582, 640582, 'Y4', 'H4') 1
(704585, 704020, 'Z2', 'G2') 1
(800035, 800035, 'G1', 'I1') 1
(200038, 200038, 'T2', 'Z4') 1
(830066, 800672, 'A1', 'Z4') 1
(260600, 260035, 'Z4', 'Y4') 1
(200013, 200013, 'T2', 'Z4') 1
(420041, 420041, 'G1', 'I1') 1
(970582, 970582, 'H4', 'Z2') 1
(100603, 100996, 'Z4', 'Y4') 1
(330583, 330583, 'Y4', 'H4') 1
(420009, 420009, 'Z1', 'G1') 1
(800034, 800034, 'Y4', 'H4') 1
(220032, 220032, 'Y4', 'H4') 1
(100601, 100601, 'X2', 'H4') 1
(400588, 400041, 'Z1', 'G1') 1
(360023, 360023, 'H4', 'Z2') 1
(800064, 800672, 'A1', 'Z4') 1
(100601, 100601, 'H4', 'T4') 1
(360009, 360009, 'Y4', 'H4') 1
(330026, 330672, 'A1', 'Z4') 1
(330014, 330014, 'T2', 'Z4') 1
(400587, 400587, 'Y4', 'H4') 1
(640017, 640017, 'Z1', 'G1') 1
(320008, 320004, 'Z2', 'G2') 1
(830063, 704672, 'A1', 'Z4') 1
(800078, 800672, 'A1', 'Z4') 1
(260600, 260600, 'Y7', 'I7') 1
(241015, 330672, 'A1', 'Z4') 1
(800017, 800017, 'A1', 'V3') 1
(320040, 320040, 'Y4', 'H4') 1
(704059, 704059, 'Y4', 'H4') 1
(100183, 100183, 'T2', 'Z4') 1
(100599, 100599, 'H4', 'Z2') 1
(800584, 800584, 'H7', 'Z4') 1
(300584, 300583, 'H4', 'Z4') 1
(540010, 540010, 'P4', 'Y4') 1
(420026, 420027, 'Z1', 'G1') 1
(400022, 400022, 'Z1', 'G1') 1
(330031, 330031, 'Z1', 'G1') 1
(420009, 420009, 'H4', 'H4') 1
(730011, 730011, 'H4', 'Z2') 1
(400065, 400065, 'G1', 'I1') 1
(100603, 100603, 'W2', 'I7') 1
(300056, 400672, 'A1', 'Z4') 1
(100026, 100026, 'G1', 'I1') 1
(330030, 330030, 'G2', 'I2') 1
(100149, 100149, 'T2', 'Z4') 1
(640032, 640032, 'Z1', 'G1') 1
(830058, 800672, 'A1', 'Z4') 1
(220066, 220066, 'T2', 'Z4') 1
(950000, 950580, 'A1', 'Z4') 1
(730013, 730013, 'Y4', 'Y4') 1
(730011, 730011, 'Y4', 'H4') 1
(100135, 100135, 'T2', 'Z4') 1
(241584, 241001, 'Z1', 'G1') 1
(330584, 330450, 'Z1', 'G1') 1
(220584, 220001, 'Z1', 'G1') 1
(220037, 220037, 'Y4', 'H4') 1
(800035, 800672, 'A1', 'Z4') 1
(800038, 800672, 'A1', 'Z4') 1
(100159, 100159, 'T2', 'Z4') 1
(400587, 400587, 'Y4', 'P4') 1
(360011, 360011, 'P4', 'Z4') 1
(800067, 800672, 'A1', 'Z4') 1
(900030, 500055, 'Y4', 'Y4') 1
(600035, 600035, 'Y4', 'H4') 1
(91814, 241021, 'Z4', 'Y4') 1
(360582, 360582, 'Y4', 'H4') 1
(950020, 950020, 'A1', 'Z4') 1
(400003, 400003, 'Y4', 'H4') 1
(220064, 220064, 'G2', 'I2') 1
(100105, 100105, 'T2', 'Z4') 1
(800029, 800672, 'A1', 'Z4') 1
(830026, 800672, 'A1', 'Z4') 1
(950017, 950580, 'A1', 'Z4') 1
(540021, 540021, 'T2', 'Z4') 1
(704035, 704035, 'G2', 'I2') 1
(704009, 704009, 'G2', 'I2') 1
(730046, 730039, 'Z4', 'Y4') 1
(400587, 400587, 'I4', 'W2') 1
(330584, 330584, 'Y4', 'H4') 1
(330584, 330004, 'Z1', 'G1') 1
(500600, 500600, 'Y4', 'H4') 1
(300600, 300583, 'Z4', 'P4') 1
(704583, 704583, 'Y4', 'H4') 1
(400022, 400022, 'G1', 'I1') 1
(200584, 200584, 'H4', 'H4') 1
(100591, 100591, 'Y7', 'I7') 1
(300015, 300015, 'G2', 'I2') 1
(400584, 400451, 'Z1', 'G1') 1
(100250, 100250, 'H4', 'Z2') 1
(704020, 704020, 'G2', 'I2') 1
(300030, 300030, 'Z2', 'G2') 1
(420026, 420026, 'Z1', 'G1') 1
(640032, 640032, 'G1', 'I1') 1
(300019, 300583, 'A1', 'P4') 1
(420009, 400672, 'Z4', 'Z4') 1
(420584, 420584, 'P4', 'Y4') 1
(100056, 100056, 'T2', 'Z4') 1
(800586, 800035, 'Y4', 'G1') 1
(320040, 320044, 'Z1', 'G1') 1
(420009, 420009, 'X2', 'H4') 1
(220026, 220026, 'T2', 'Z4') 1
(241584, 241584, 'H4', 'Z2') 1
(800033, 800672, 'A1', 'Z4') 1
(400601, 400034, 'Z1', 'G1') 1
(420032, 420032, 'Z1', 'G1') 1
(800028, 800672, 'A1', 'Z4') 1
(420030, 420030, 'T2', 'Z4') 1
(200600, 200600, 'H4', 'Z2') 1
(200005, 200005, 'T2', 'Z4') 1
(241041, 330672, 'A1', 'Z4') 1
(704585, 704004, 'Z2', 'G2') 1
(100051, 100051, 'G1', 'I1') 1
(100601, 100149, 'Z1', 'G1') 1
(400589, 400589, 'Y4', 'H4') 1
(830011, 830011, 'A1', 'V3') 1
(704037, 704037, 'G2', 'I2') 1
(100118, 100118, 'G1', 'I1') 1
(241022, 330672, 'A1', 'Z4') 1
(500002, 500002, 'T2', 'Z4') 1
(241584, 241584, 'P4', 'Y4') 1
(241021, 241021, 'H4', 'Z4') 1
(300037, 400672, 'A1', 'Z4') 1
(100183, 91813, 'Z4', 'Z4') 1
(220602, 220602, 'H4', 'Z2') 1
(241056, 241056, 'Y4', 'H4') 1
(830025, 800672, 'A1', 'Z4') 1
(900001, 800672, 'A1', 'Z4') 1
(800584, 800584, 'Y7', 'I7') 1
(900064, 900063, 'Z1', 'G2') 1
(241601, 241021, 'Z4', 'Y4') 1
(730028, 730031, 'Z2', 'G2') 1
(704584, 704028, 'Z2', 'G2') 1
(241602, 241602, 'H4', 'H4') 1
(830584, 830584, 'X2', 'H4') 1
(704585, 704062, 'Z2', 'G2') 1
(400451, 400451, 'G1', 'I1') 1
(400584, 400584, 'V2', 'P4') 1
(704583, 704583, 'H4', 'Y4') 1
(100087, 100087, 'T2', 'Z4') 1
(540028, 540028, 'Y4', 'Y4') 1
(970007, 970007, 'T2', 'Z4') 1
(500045, 500045, 'G1', 'I1') 1
(200026, 200584, 'A1', 'P4') 1
(830002, 800672, 'A1', 'Z4') 1
(970031, 970582, 'Z4', 'Z4') 1
(300584, 300584, 'Y7', 'I7') 1
(800053, 800672, 'A1', 'Z4') 1
(220047, 220047, 'G2', 'I2') 1
(970021, 970021, 'T2', 'Z4') 1
(800585, 800078, 'Z2', 'G2') 1
(360000, 360000, 'G1', 'I1') 1
(400584, 400045, 'Z1', 'G1') 1
(220583, 220583, 'H4', 'P4') 1
(800582, 800582, 'Y4', 'H4') 1
(330586, 320002, 'Z2', 'G2') 1
(400002, 400672, 'A1', 'Z4') 1
(400584, 400040, 'Z1', 'G1') 1
(330002, 330002, 'Y4', 'H4') 1
(800055, 800672, 'A1', 'Z4') 1
(300047, 300047, 'Z1', 'G1') 1
(704583, 704583, 'P5', 'P5') 1
(900020, 900020, 'G2', 'I2') 1
(704600, 704600, 'H4', 'Z4') 1
(704013, 704013, 'G2', 'I2') 1
(800586, 800586, 'P5', 'P5') 1
(330586, 320450, 'Z1', 'G1') 1
(300010, 400672, 'A1', 'Z4') 1
(400008, 400006, 'Z1', 'G1') 1
(100031, 100031, 'G2', 'I2') 1
(420600, 420045, 'Y4', 'G2') 1
(800062, 800672, 'A1', 'Z4') 1
(420018, 420018, 'Y4', 'H4') 1
(420009, 420009, 'Y4', 'H4') 1
(830040, 800672, 'A1', 'Z4') 1
(300047, 300047, 'G1', 'I1') 1
(800085, 800672, 'A1', 'Z4') 1
(100602, 100602, 'I4', 'P5') 1
(241021, 241021, 'X2', 'H4') 1
(100564, 100564, 'Y4', 'H4') 1
(300047, 400672, 'A1', 'Z4') 1
(420043, 420043, 'S2', 'Z4') 1
(300600, 300600, 'Y4', 'Y4') 1
(320014, 320014, 'T2', 'Z4') 1
(91814, 220601, 'Z4', 'Y4') 1
(200024, 200024, 'Y4', 'H4') 1
(100029, 100029, 'T2', 'Z4') 1
(91813, 100108, 'Z4', 'G2') 1
(100602, 100602, 'Y4', 'V2') 1
(704672, 730007, 'Z4', 'Y4') 1
(330031, 330031, 'Y4', 'Y4') 1
(830003, 800672, 'A1', 'Z4') 1
(100587, 100587, 'Y4', 'Y4') 1
(100581, 100026, 'Z1', 'G1') 1
(704600, 704600, 'H4', 'Z2') 1
(100572, 91813, 'Z4', 'Z4') 1
(241601, 241601, 'Y4', 'H4') 1
(800001, 800672, 'A1', 'Z4') 1
(220600, 220041, 'Z1', 'G1') 1
(704585, 704037, 'Z2', 'G2') 1
(800041, 800672, 'A1', 'Z4') 1
(704600, 704672, 'Z4', 'Z4') 1
(330585, 330585, 'V2', 'Z4') 1
(400588, 400027, 'Z1', 'G1') 1
(241021, 241021, 'Y4', 'V2') 1
(241602, 241602, 'Y4', 'H4') 1
(500055, 100029, 'Y4', 'G2') 1
(970031, 970031, 'T2', 'Z4') 1
(220600, 220600, 'Y4', 'Y4') 1
(400584, 400584, 'Y4', 'H4') 1
(704011, 704672, 'A1', 'Z4') 1
(241020, 330672, 'A1', 'Z4') 1
(800025, 800672, 'A1', 'Z4') 1
(800584, 800672, 'Z4', 'Z4') 1

In [297]:
kml.save("test.kml")